### ISSUE TITLE
add butcher methods

### ISSUE THREAD

**Issue by topepo** [tidymodels/stacks#10]
To trim out extra stuff that is not needed to make predictions.

**Comment by simonpcouch** [comment]
From what I can tell, these differences in object sizes are about what they should be. Closing for now. :-)

``` r
library(stacks)

reg_st <- 
  stacks() %>%
  add_candidates(reg_res_lr) %>%
  add_candidates(reg_res_svm) %>%
  blend_predictions() %>%
  fit_members()

lobstr::obj_size(reg_st)
#> 2,930,144 B

lobstr::obj_size(butcher(reg_st))
#> 992,016 B
```

<sup>Created on 2020-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
