### ISSUE TITLE
Stacks specific models

### ISSUE THREAD

**Issue by mvt-oviedo** [tidymodels/stacks#107]

**Comment by mvt-oviedo** [comment]
Hi,
Very good package.

I was wondering if it is possible selecting specif models to ads_models() instead of all models or if this functionality does not exist.

For example:

data(bivariate)
BD <- bivariate_train

set.seed(123)
  data_split <- initial_split(BD, prop = 0.8, strata = Class)
  train_data <- training(data_split)
  test_data  <- testing(data_split)

BD_rec <- recipe(Class ~., data = train_data) %>%
   step_zv(all_predictors()) %>% 
   step_normalize(all_predictors())

set.seed(123)
  folds <- vfold_cv(train_data, v = 10, strata = Class)
  initial <- 10
  iter <- 50
  mejora <- 5
  metrica <- metric_set(roc_auc)
  ctrl_bayes <- control_bayes(no_improve = mejora,
                              save_pred = TRUE,
                              save_workflow = TRUE,
                              verbose = TRUE)
    
  svm_mod <-
    svm_rbf(mode = "classification",
            cost = tune(),
            rbf_sigma = tune()) %>%
    set_engine("kernlab")
  
  svm2_mod <-
    svm_linear(mode = "classification",
               cost = tune()) %>%
    set_engine("kernlab")

svm_wflow <-
    workflow() %>%
    add_model(svm_mod) %>%
    add_recipe(BD_rec)
  
  svm2_wflow <-
    workflow() %>%
    add_model(svm2_mod) %>%
    add_recipe(BD_rec)

set.seed(123)
  search_svm <-
    svm_wflow %>% 
    tune_bayes(
      resamples = folds,
      initial = initial,
      iter = iter,
      metrics = metrica,
      control = ctrl_bayes
    )
  
  set.seed(123)
  search_svm2 <-
    svm2_wflow %>% 
    tune_bayes(
      resamples = folds,
      initial = initial,
      iter = iter,
      metrics = metrica,
      control = ctrl_bayes
    )

stacks()
  
  super <- 
    stacks() %>%
    add_candidates(search_svm) %>%
    add_candidates(search_svm2) %>%
    blend_predictions(metric = metrica,
                      mixture = c(0, 0.25, 0.5, 0.75, 1)) %>%
    fit_members()

I want to select de best models from search_svm and search_svm2 instead of all models from theese. But I do not know whats is the proper way if it is possible.

Many thanks,

**Comment by simonpcouch** [comment]
Thanks for the issue! {stacks} will do the work of weighting (and often zero-ing out weights for) specific models in your `search_svm` and `search_svm2` model specs at the `blend_predictions` step. If you'd like {stacks} to only evaluate a subset of them, write out those hyperparameter grids explicitly in your calls to {tune} functions.
