### ISSUE TITLE
address dependencies NOTE

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/stacks#115]
Currently seeing:

```
❯ checking package dependencies ... NOTE
  Imports includes 21 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.
```

after introducing `kernlab` dependency using in example objects and examples. I think it should stay (and this NOTE is not actually a worry—we maintain most of the Imports), but:

* `generics` could probably go pretty easily, just namespacing with re-exports
* `cli` functions only used once or twice—could copy+paste definitions

**Comment by juliasilge** [comment]
If kernlab is used only in examples, you could keep it in Suggests [and use `@examplesIf`](https://github.com/tidymodels/vetiver-r/blob/main/R/ptype.R#L34-L37).
