### ISSUE TITLE
rename stack_fit

### ISSUE THREAD

**Issue by topepo** [tidymodels/stacks#13]
I understand the process of creating one of these ensembles but I think people are going to confuse `stack_blend()` and `stack_fit()`. I would suggest going back to something like `stack_fit_members()`

**Comment by mdancho84** [comment]
What about just fit(). Workflows and parsnip both use fit() so it’s consistent.

**Comment by simonpcouch** [comment]
I’m not sure I agree that this will be as confusing for new users.

With errors that are informative/thoughtful enough (a la 00c4329), I think this confusion could be clarified relatively quickly.

If we feel like `stack_blend()` and `stack_fit()` are still too difficult to delineate, though, I think it’s worth revisiting each of the three “core verbs” — I’d prefer they have the same grammatical structure. Some possibilities:
* `stack_fit_members()`, `stack_blend_candidates()`, `stack_add_candidates()`
* `fit_members()`, `blend_candidates()`, `add_candidates()`
* `fit()`, `blend()`, and something else

Open to more discussion.🙂

**Comment by mdancho84** [comment]
Disregard my previous comment. Given these are the core workflow functions - I’m a fan of including `stack_` at the beginning. It will make it easier for users to search for the functions and help with name recognition, which eventually turns into muscle memory the more they type these functions. 

So my vote is for `stack_fit()` or `stack_fit_members()`. `stack_fit()` is the direction I’d lean just to keep things short and sweet.

**Comment by simonpcouch** [comment]
Starting to lean towards `fit_members()`, `blend_candidates()`, `add_candidates()`—I agree that we should make sure we're delineating between `stack_fit()` and `stack_blend()` as clearly as possible while we're still able to take a step like changing the names of these functions. 

The name for `blend_candidates()` could possibly be more metalearner-centered than candidate-centered, too. Possibly something like `blend_model()`, `blend_stack()`, `blend_predictions()`, etc.

Coming back to this after a few weeks, too, the stutter of `stacks::stack_*()` is less appealing to me. I see your point of taking advantage of tab completion, @mdancho84, but feel that it's less important when the number of functions is as few as it is here.
