### ISSUE TITLE
recycle metric_sets

### ISSUE THREAD

**Issue by topepo** [tidymodels/stacks#16]
Since the `tune_*` objects have an embedded metric set, use the same object in the `glmnet` fit. (this is probably contrary to what I suggested at the start. Sorry).

**Comment by simonpcouch** [comment]
Where is the metric set embedded? It seems to me the `metric_set` ids can be found in `resampling_results[[".metrics"]][[1]][[".metric"]]`, but different candidate sets can have different metrics. (See `reg_res_lr` and `reg_res_svm` exported with the package.) Maybe this should be something we check for? If not, do we use all metrics used by any of the candidate sets?
