### ISSUE TITLE
Vignette missing `update_recipe()`

### ISSUE THREAD

**Issue by pbulsink** [tidymodels/stacks#187]
In the vignette "Classification Models With stacks", the recipe for preprocessing for the neural network model is updated (to the variable `nnet_rec`) but that updated recipe is never used or implemented anywhere. I have gathered that the `nnet_wflow` variable should be created as such (note the addition of the `update_recipe()` line):

```
nnet_wflow <- 
  tree_frogs_wflow %>%
  add_model(nnet_spec) %>%
  update_recipe(nnet_rec)
```

This should be added in the code block starting on line 141.

Thanks!

**Comment by simonpcouch** [comment]
Hey there! I think you're right—will make sure to get to this before the next release. :)

Permalink:

https://github.com/tidymodels/stacks/blob/60cd57d0d2eae9d69f3a0bd08977d735bfe541ca/vignettes/classification.Rmd#L147-L153
