### ISSUE TITLE
Update example data objects for new recipes

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/stacks#203]
I use some of the stacks data objects like `reg_res_lr` in setting up tests in vetiver, and I see these warnings about `keep_original_cols`:

``` r
library(stacks)

data("tree_frogs", package = "stacks")
tree_test <- tree_frogs %>%
    dplyr::select(-hatched, -latency, -clutch)

frog_reg <-
    stacks() %>%
    add_candidates(reg_res_lr) %>%
    add_candidates(reg_res_sp) %>%
    blend_predictions(penalty = 20) %>%
    fit_members()
#> Warning: 'keep_original_cols' was added to `step_ns()` after this recipe was created.
#> Regenerate your recipe to avoid this warning.
#> 'keep_original_cols' was added to `step_ns()` after this recipe was created.
#> Regenerate your recipe to avoid this warning.
#> 'keep_original_cols' was added to `step_ns()` after this recipe was created.
#> Regenerate your recipe to avoid this warning.
```

<sup>Created on 2023-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Do you think these objects could be regenerated so they don't generate warnings with the current version of recipes?

**Comment by simonpcouch** [comment]
Absolutely. Will loop this into stacks' spring cleaning and put together a release with changes from the last few months after then. :)

**Comment by simonpcouch** [comment]
Will wait a few days before sending these changes off to CRAN, @juliasilge—feel free to holler if this doesn't do the trick for your tests, but it resolved the same issue in stacks' tests!
