### ISSUE TITLE
Adding stratification to bootstrapping in blend_predictions

### ISSUE THREAD

**Issue by TSI-PTG** [tidymodels/stacks#226]
It would be ideal if the user could implement stratification for the resampling procedure when obtaining the stacking coefficients with blend_predictions() to better handle rare events in classification settings. I would think some users would also appreciated the option for v-fold resampling with blend_predictions() as well.

**Comment by simonpcouch** [comment]
Thanks for the issue!

This issue shares some sentiment with #199, so I'll go ahead and close in favor of discussion there—will make sure and keep this in mind if we revisit the interface to `blend_predictions()` at some point.
