### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by realauggieheschmeyer** [tidymodels/stacks#26]
I don't know if this has anything to do with this package still being in the development phase, but I get an error when I run the install code from the README.

``` r
remotes::install_github("tidymodels/stacks")
#> Using github PAT from envvar GITHUB_PAT
#> Error: Failed to install 'unknown package' from GitHub:
#>   HTTP error 404.
#>   No commit found for the ref master
#> 
#>   Did you spell the repo owner (`tidymodels`) and repo name (`stacks`) correctly?
#>   - If spelling is correct, check that you have the required permissions to access the repo.
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is this an intentional feature right now? 

Thank you.

**Comment by juliasilge** [comment]
The default git branch of this repo is named `main`, and `remotes::install_github()` doesn't support names for the default except for `master` right now.

The best way to install this package for the time being is to clone it locally and then build it.

**Comment by simonpcouch** [comment]
Thanks for the issue! 

Yeah, as Julia noted, `install_github()` will trip up on the default branch being `main`. I didn't test this out when I wrote the README code, so I'll update this now, but you should be able to specify which branch you want to install from with the `ref` argument!

```
remotes::install_github("tidymodels/stacks", ref = "main")
```

Probably worth noting as well that the package will be pretty unstable (both in terms of ability to install and API) as we get core functionality in place.🙂

**Comment by realauggieheschmeyer** [comment]
Thank you @juliasilge and @simonpcouch. I didn't expect to use the package for any production-ready modeling yet, but I'm excited to play around with it.

**Comment by simonpcouch** [comment]
The interest is much appreciated!🐛

**Comment by juliasilge** [comment]
Ooops, I was wrong! Apologies!!
