### ISSUE TITLE
Parallel Processing Considerations - Blend Predictions, Tune Grid Control

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/stacks#34]
Just adding a note here to consider parallel processing when using [`tune_grid`](https://github.com/tidymodels/stacks/blob/41300420415556553a9078c7d281b8800f720fe8/R/blend_predictions.R#L135). 

A possible way to handle is to elevate / create an extension of the `tune::control_grid()` to the function that allows access to the `allow_par` argument:

```
blend_predictions <- function(data_stack, penalty = 10 ^ (-6:-1), verbose = FALSE, ..., control = control_blend(allow_par = TRUE)) {...}
```

Where `control_blend` is:

```
#' @export 
control_blend <- function(verbose = FALSE, allow_par = TRUE, pkgs = NULL) {
   get_models <- function(x) {
      x %>% 
          workflows::pull_workflow_fit() %>% 
          purrr::pluck("fit")
    }

    tune::control_grid(save_pred = TRUE, extract = get_models, verbose = verbose, allow_par = allow_par, pkgs = pkgs)
}
```

**Comment by simonpcouch** [comment]
Thanks for the issue and for your patience on this! Just PRed support for parallel processing in #42 for both `blend_predictions()` and `fit_members()`—the implementation for `blend_predictions()` looks quite a bit like your suggestion! Give it a go and let us know what you think. :-)
