### ISSUE TITLE
General thoughts and suggestions on stacks

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/stacks#41]
Hi @simonpcouch,

Cool new package! I've been playing around with it for a little and I like the API a lot and I have a few suggestions/comments:

- I think the documentation for `blend_predictions()` can be improved by spending a few sentences explaining a little more about what happens under-the-hood (i.e. a LASSO is fit to 25 bootstrap resamples of the `as_tibble(data_stack)` object passed to `blend_predictions()`). I figured things out by looking into the source code, but without doing that it was a little opaque about what exactly was going on to get the stacking weights.

- Also I'm wondering if it might be worth specifically noting in the documentation that the `weights` are betas/coefficients from the LASSO. 

- Semantics: `Out of 15 possible blending coefficients, the ensemble used 5.` I wonder if its clearer to use retained/identified/selected instead of _used_ in this context? Or maybe even `Out of 15 possible sub-models, the ensemble includes 5.`. I'm just thinking out loud.

- Even after playing around with the functions I'm still not crystal clear on `fit_members()` purpose. The documentation does little to resolve my confusion. I think this function specifically could use some documentation improvements.

- The `Example Data` section is very informative, but it appears in so many of the help docs for various functions that it sorta obfuscates the documentation relevant specifically to that function. Just an observation.

**Comment by simonpcouch** [comment]
Thanks for the issue! Your thoughts are much appreciated, and I agree on many of your points.

 Will get to this in a bit.

**Comment by simonpcouch** [comment]
Alright, made some edits!

328e117 (currently only on the `parallel` branch, merging in the next few days) overhauls the help-files for the main verbs and hopefully gets at some of your concerns. The print method clarification is on `main`. Very much open to thoughts if you think there are some parts of the process that still need clarification! Closing for now. :-)

**Comment by mattwarkentin** [comment]
Just read over the updates to the help docs and everything looks great! It is much clearer to me now how each step fits in the whole process.
