### ISSUE TITLE
Picking the best model

### ISSUE THREAD

**Issue by ericpgreen** [tidymodels/stacks#49]
Is this statement correct:

> As we can see, the stacked ensemble outperforms each of the member models, though is closely followed by one of the spline members.

<img width="828" alt="Screen Shot 2020-11-04 at 11 21 01 AM" src="https://user-images.githubusercontent.com/546433/98137355-e4a35c80-1e8f-11eb-9412-d7c3b1eaecf7.png">

I interpret the table to mean that the rmse for the ensemble is 43.7 and the best spline member is 43.1. If the best model has the lowest rmse, wouldn't the spine member be the best? Or have I misunderstood this table? 

Source: [https://stacks.tidymodels.org/articles/basics.html](https://stacks.tidymodels.org/articles/basics.html)

**Comment by simonpcouch** [comment]
Ah, looks like I missed something reproducibility-wise. 

Just to help narrow down what kind of `set.seed()` trouble we're looking at, what is your R version?

**Comment by ericpgreen** [comment]
I did not actually run it. Just reading the results off the table on the webpage.

**Comment by simonpcouch** [comment]
Ope, gotcha.😄 Will troubleshoot here in a bit. Thanks for the issue!

**Comment by ericpgreen** [comment]
Thanks! Interpreting my own results and I wanted to make sure I understand your example.

**Comment by simonpcouch** [comment]
This was corrected in the [revamped Getting Started vignette](https://stacks.tidymodels.org/articles/basics.html)!

Thanks for noting this.
