### ISSUE TITLE
Non-linear metalearning algorithms

### ISSUE THREAD

**Issue by ledell** [tidymodels/stacks#54]
## Non-linear metalearning algorithms

_Hey, sorry I meant to post this about a month ago when I was first exploring the package, and then I got lost in the election drama and forgot to follow up. :-/  I saw that stacks just made it to CRAN (congrats!) so it reminded me to write it up and post here (I had hoped to provide this feedback before it went to CRAN)._

The structure of the output objects (as well as the language used in the docs) presumes that a linear model will be used for the metalearning algorithm (there's a focus & dependency on there being coefficients/weights for the base learners).  In the [`blend_predictions()`](https://stacks.tidymodels.org/reference/blend_predictions.html) function, the metalearner algorithm is pre-specified as a Lasso GLM (not configurable to the user).  In general, stacking can use any type of supervised algorithm as the metalearner (blending algorithm), so even if you choose to hard-code the algo to using a Lasso GLM for a metalearning algorithm, it might be worth considering (maybe you have already?) whether you want to add some abstraction layer so that the structure of the output does not depend on the ensemble being a linear/weighted stack of the base models (in case you want to extend the functionality later).  Do you have plans to extend this to any type of algorithm for a metalearner, or do you see this being a fixed component of the stacking implementation in **stacks**?

While a GLM with some regularization is my go-to metalearner as well (and the default in H2O's Stacked Ensemble algo), there are a lot of cases where other algorithms will produce a better stacked ensemble (see Kaggle for examples).  In [`h2o::h2o.stackedEnsemble()`](http://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.stackedEnsemble.html), we allow the user to customize the metalearning algorithm, and we use an Elastic-Net GLM as the default.  Metalearner flexibility is also offered in the original stacking R package, [SuperLearner](https://github.com/ecpolley/SuperLearner), via the `method` argument (defaults to linear model fit via non-negative least squares).  I think there's a lot of utility in allowing people to customize their metalearning method (and removing the dependency on linear models).

**Summary:** If you had planned to allow the user to specify their own metalearner at some point in the future (or want to keep the option open), it might be worth re-structuring the output to remove the dependency on having a linear model for metalearning.   

**Recommendation for docs:** Right now it reads as if GLM as the metalearner is an unchangeable or native aspect of the the stacked ensemble algorithm, so it might be good to add some extra context for the reader who is new to stacking to clarify that this is just one algo that can be used for metalearning.

**Comment by simonpcouch** [comment]
Thank you for bringing this up! All is well on the timing—I'm sure many of us can relate to getting caught up in the political situation recently. :-)

 I'll get back to this in a week or so!

**Comment by simonpcouch** [comment]
Okay, right! Thank you for bringing this up! Wanted to make sure to chat with Max & Kelly about this before responding to make sure we were on the same page.

For now, our plan is to stick with only supporting GLMs as a metalearning algorithm in stacks. Briefly, 

* GLMs with some regularization are our go-to as well.
* I feel that the choice of a specific metalearner helped us format outputs and write documentation in a particularly explainable way.
* I currently don't have the resources to implement/maintain functionality for other metalearning algorithms. (This package is my undergrad thesis—I'll need to pivot over to writing something more thesis-like next semester.😄)

I agree that abstracting beyond GLMs would be the next step for extending ensembling functionality in the tidymodels. Perhaps a tidymodels interface to h2o.ai could be a worthwhile pursuit for one to take on. :-) 

Very much agreed that I should clarify documentation related to the possibility of other metalearning algorithms. A link out to `h2o::h2o.stackedEnsemble()` might be worthwhile here. Will push a related commit here in a bit!

**Comment by ledell** [comment]
@simonpcouch Thanks for the response!  Yes, I'd love to see tidymodels <-> h2o integration. 😎

Do you want me to close the ticket (since there's no plan to do this now) or leave it open (since it sounds like it might be a possible extension at some point in the future)?

**Comment by simonpcouch** [comment]
I'll go ahead and close this issue for now.🦋 Thanks again!
