### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by marlycormar** [tidymodels/stacks#59]
Hi @simonpcouch, awesome package! 

This issue is mainly a comment regarding the DESCRIPTION file of the package. Playing around with another package ([`riskmetric`](https://github.com/pharmaR/riskmetric)), I noticed that the DESCRIPTION file of stacks doesn't have a Bug Reports url. I am not sure if this is intended, but I just wanted to let you know.

**Comment by simonpcouch** [comment]
Ah, thanks for the issue! Will add that to the DESCRIPTION here in a sec.☃️
