### ISSUE TITLE
autoplot(type = "members") has facets on same y-axis

### ISSUE THREAD

**Issue by topepo** [tidymodels/stacks#77]
[original post](https://community.rstudio.com/t/tidymodels-stacks-autoplot-with-type-members/99786)

``` r
library(stacks)

# put together a data stack
reg_st <- 
  stacks() %>%
  add_candidates(reg_res_lr) %>%
  add_candidates(reg_res_svm) %>%
  add_candidates(reg_res_sp)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip

reg_st <- 
  reg_st %>%
  blend_predictions()

autoplot(reg_st, type = "members")
```

![](https://i.imgur.com/mcL2iuX.png)

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9000)</sup>

**Comment by simonpcouch** [comment]
I agree with @llendway's recommendation! Thanks so much for your thoughts here.

Just made some changes (PRing in a sec), and here is what the result would look like now:

``` r
library(stacks)

reg_st <- 
  stacks() %>%
  add_candidates(reg_res_lr) %>%
  add_candidates(reg_res_svm) %>%
  add_candidates(reg_res_sp) %>%
  blend_predictions()

autoplot(reg_st, type = "members")
```

![](https://i.imgur.com/MMPS8zL.png)

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>


I think this is much more informative. Let us know if this isn't what you had in mind, Dr. Lendway.

Thanks for reposting, Max. :-)

**Comment by llendway** [comment]
This is perfect! Wow, thanks for doing that so quickly.

**Comment by simonpcouch** [comment]
Glad to hear it. Okay, merging to the main dev branch!
