### ISSUE TITLE
fit_models() fails on multiclass predictions if the classes aren't valid R variable names

### ISSUE THREAD

**Issue by dgrtwo** [tidymodels/stacks#88]
## The problem

When predicting a multiclass factor, `fit_members()` fails if the outcome includes levels that aren't valid R variable names (e.g. they include spaces or punctuation). It fails with the message:

```
task 1 failed - "`parameters` objects cannot be created from this type of object."
``` 

A little experimentation indicates that this is because a full_join fails and leaves NAs in a "name" column whenever an outcome level is not a valid variable name (see below).

## Reproducible example

```r
library(tidymodels)
library(stacks)
library(palmerpenguins)

# change the species so that it has a - in it (any special character will do).
dat <- penguins %>%
  mutate(species = paste0(species, "-1"))

# Create three versions with different penalty parameters
tuned <- recipe(species ~ bill_length_mm + bill_depth_mm +
                  flipper_length_mm, data = dat) %>%
  step_impute_mean(all_numeric_predictors()) %>%
  workflow(multinom_reg(engine = "glmnet", penalty = tune())) %>%
  tune_grid(dat %>% vfold_cv(3),
            metrics = metric_set(mn_log_loss),
            grid = crossing(penalty = c(.0001, .001, .01)),
            control = control_stack_grid())

# Blending the predictions works
blended <- stacks() %>%
  add_candidates(tuned) %>%
  blend_predictions()

# However, fitting the models does not
fit <- blended %>%
  fit_members()
```

The above gets the error

``` Error in { : 
  task 1 failed - "`parameters` objects cannot be created from this type of object.
```

It works fine if I didn't include the `species = paste0(species, "-1")` step, and it breaks on every "wouldn't be a valid variable name" change I've made to the outcome.

### More detail

The traceback is:

```5.
stop(simpleError(msg, call = expr)) 
4.
e$fun(obj, substitute(ex), parent.frame(), e$data) 
3.
foreach::foreach(mem = member_names, .inorder = FALSE) %do_op% 
    {
        asNamespace("stacks")$fit_member(name = mem, wflows = model_stack[["model_defs"]], 
            members_map = members_map, train_dat = dat) ... at fit_members.R#118
2.
fit_members(.) 
1.
blended %>% fit_members() 
```

The foreach obscures the line where the error is happening, which is this step in `fit_member()`:

```
  member_params <- 
    wflows[[member_row$name.x[1]]] %>%
    dials::parameters() %>%
    dplyr::pull(id)
```

That happens because `member_row$name.x[1]` is NA, so `wflows[[member_row$name.x[1]]]` is NULL. With a little experimentation, I realized this happens because a join is failing whenever an outcome level isn't valid R syntax. (Something about sanitizing the class names doesn't seem to be working). That's basically where my understanding of the problem ends.

**Comment by juliasilge** [comment]
Ah, I ran into this this at one point! 🙌

**Comment by simonpcouch** [comment]
Thank you for the issue and careful description! I agree that this needs addressing.  Been away from my computer for a bit and will be catching back up on open source in the latter half of this next work week—thanks for your patience. :-)
