### ISSUE TITLE
Enable add_candidate() to construct members from individual data columns

### ISSUE THREAD

**Issue by simonschoe** [tidymodels/stacks#91]
## Feature

Currently, new candidates are added to a `stacks()` object using `add_candidates()` by providing a fitted `tune_results` or `resample_results` object.

Let's assume that aside form all the model predictions I also have an expert estimates in my data as a separate variable/column (similar to the prediction model, the human was also asked to give an educated guess for the response). Would it be possible to use `add_candidates()` in a way that also allows me to integrate expert estimates (depicted by single column in my underlying data) as an additional "base model" into my meta model, i.e. the stacked model? In particular, I am curious how much weight the expert estimate would be assigned to by the meta learner. I am not sure though, how this could look like programmatically...

**Comment by simonpcouch** [comment]
Thanks for the issue! 

As proposed, I'm not sure how this functionality could be implemented in practice. At a high level, I don't anticipate any issues in the `blend_predictions` step—the meta learner should be able to assign weights to that column—though the actual bookkeeping that `stacks` makes happen in the backend for the tuning results objects would likely fail if one were to manually add a column with those expert estimates to the `data_stack` before blending predictions. The biggest challenge implementation-wise, though, is that it's unclear to me how that "expert estimate" member would supply predictions on new data.

An interesting question one could pursue is how this kind of expert estimate could be encoded as a tidymodels model definition, though this is outside of the scope of this package/thread.

Closing for now, but thanks again. :-)
