### ISSUE TITLE
Is there any chance that finetune and stacks will be connected in the future?

### ISSUE THREAD

**Issue by amazongodman** [tidymodels/stacks#92]
stacks receives a model that has been performance evaluated by a resample object.

The race function of finetune also uses the sample object.

Is it possible to add this to stacks()?

For example

```
control_stack_race()
control_stack_sim()

tune_race_anova(my_workflow,
                             resamples = my_v_fold,
                             grid = 3,
                             control = control_stack_race())
```

I would like to know if this is possible.

**Comment by amazongodman** [comment]
save_pred = TRUE, save_workflow = TRUE
So you can use it for stacks when you use
Thank you very much!

**Comment by simonpcouch** [comment]
Thanks for the issue @amazongodman, and thank you for the help, @juliasilge. :-)
