### ISSUE TITLE
extratests failure

### ISSUE THREAD

**Issue by topepo** [tidymodels/stacks#99]
Probably an unexpected side-effect of #95.

The [error](https://github.com/tidymodels/extratests/runs/4723555066?check_suite_focus=true#step:10:401) is: 

```
══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure (test-stacks-columns.R:37:3): stacks can accommodate outcome level
`data_st <- stacks() %>% add_candidates(tuned)` produced warnings.
```

**Comment by simonpcouch** [comment]
Just wanted to note that I've seen this—having trouble reproducing this warning but will try to get back to this sooner than later.

**Comment by simonpcouch** [comment]
And thanks for letting me know!

**Comment by simonpcouch** [comment]
Ah, no biggie. The warning is due to a deprecation in `workflows`:

```
1. stacks can accommodate outcome levels that are not valid colnames (test-stacks-columns.R:37:3) - 

`pull_workflow_preprocessor()` was deprecated in workflows 0.2.3.
Please use `extract_preprocessor()` instead.
```

Will PR on stacks and extratests soon.
